modLoader="javafml"
loaderVersion="${loader_version_range}"

license="MIT"
issueTrackerURL="https://github.com/boatboatboatboatboat/industrialhellscape"

[[mods]]

modId="industrialhellscape"
version="${mod_version}"
displayName="Industrial Hellscape"
logoFile="logo_for_mods_toml_file.png"
authors="YellowUboat"

description='''Industrial-themed Minecraft decor mod.'''

[[dependencies.industrialhellscape]]
    modId="forge" #mandatory
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.industrialhellscape]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
