package net.boat.industrialhellscape.block.modded_block_classes.Experimental;

import net.boat.industrialhellscape.block.modded_block_entities.ModBlockEntities;
import net.boat.industrialhellscape.block.modded_block_entities.RecyclerBE;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.BaseEntityBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.RenderShape;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityTicker;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.BooleanProperty;
import net.minecraft.world.level.block.state.properties.DirectionProperty;
import net.minecraft.world.phys.BlockHitResult;
import org.jetbrains.annotations.Nullable;

public class RecyclingBlock /*extends BaseEntityBlock*/ {
//    public static final DirectionProperty FACING = BlockStateProperties.HORIZONTAL_FACING;
//    public static final BooleanProperty POWERED = BlockStateProperties.POWERED;
//
//    public RecyclingBlock(Properties pProperties) {
//        super(pProperties);
//        this.registerDefaultState(this.stateDefinition.any()
//                .setValue(FACING, Direction.NORTH)
//                .setValue(POWERED, false)
//
//        ); //Default state if placed with no player present
//
//    }
//
//    //Placement Faces the player
//    @Override
//    public @Nullable BlockState getStateForPlacement(BlockPlaceContext pContext) {
//        Direction directionClicked = pContext.getHorizontalDirection().getOpposite(); //Gets the cardinal direction when player places new block
//        //The autogenerated block item models show the "front" of the block as the right side relative to GUI screen.
//        //In-world, this side faces away from the player when placed, which is not intuitive.
//        //getOpposite() is used to rectify in-world placement while keeping any auto-generated asymmetric textured full-block models consistent.
//
//        BlockState state = this.defaultBlockState().setValue(FACING, directionClicked); //First, defines facing direction of the block
//        state = state.setValue(POWERED, Boolean.valueOf(pContext.getLevel().hasNeighborSignal(pContext.getClickedPos()))); //Secondly, sets redstone power status for block
//        return state;
//    }
//
//    public void neighborChanged(BlockState pState, Level pLevel, BlockPos pPos, Block pBlock, BlockPos pFromPos, boolean pIsMoving) {
//        if (!pLevel.isClientSide) {
//            boolean flag = pLevel.hasNeighborSignal(pPos);
//            if (flag != pState.getValue(POWERED)) {
//                pLevel.setBlock(pPos, pState.setValue(POWERED, Boolean.valueOf(flag)), 2);
//            }
//
//        }
//    }
//
//    @Override
//    protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> pBuilder) {
//        pBuilder.add(FACING, POWERED); //Block's blockstates; its NSEW orientation, its connection type defined
//    }
//
//    @Override
//    public RenderShape getRenderShape(BlockState pState) {
//        return RenderShape.MODEL;
//    }
//
//    @Override
//    public void onRemove(BlockState pState, Level pLevel, BlockPos pPos, BlockState pNewState, boolean pIsMoving) {
//        if (pState.getBlock() != pNewState.getBlock()) { //If the state changes, drop items inside it (intended for when block is removed)
//            BlockEntity blockEntity = pLevel.getBlockEntity(pPos);
//            if (blockEntity instanceof RecyclerBE) {
//                ((RecyclerBE) blockEntity).drops();
//            }
//        }
//
//        super.onRemove(pState, pLevel, pPos, pNewState, pIsMoving);
//    }
//
//    @Override
//    public InteractionResult use(BlockState pState, Level pLevel, BlockPos pPos, Player pPlayer, InteractionHand pHand, BlockHitResult pHit) {
//        if (!pLevel.isClientSide()) {
//            BlockEntity entity = pLevel.getBlockEntity(pPos);
//            if(entity instanceof RecyclerBE) {
//                NetworkHooks.openScreen(((ServerPlayer)pPlayer), (RecyclerBE)entity, pPos);
//            } else {
//                throw new IllegalStateException("Our Container provider is missing!");
//            }
//        }
//
//        return InteractionResult.sidedSuccess(pLevel.isClientSide());
//    }
//
//    @Nullable
//    @Override
//    public BlockEntity newBlockEntity(BlockPos pPos, BlockState pState) {
//        return new RecyclerBE(pPos, pState);
//    }
//
//    @Nullable
//    @Override
//    public <T extends BlockEntity> BlockEntityTicker<T> getTicker(Level pLevel, BlockState pState, BlockEntityType<T> pBlockEntityType) {
//        if(pLevel.isClientSide()) {
//            return null;
//        }
//
//        return createTickerHelper(pBlockEntityType, ModBlockEntities.RECYCLER_BLOCK_ENTITY.get(),
//                (pLevel1, pPos, pState1, pBlockEntity) -> {
//                    if (pState1.getValue(POWERED)) pBlockEntity.tick(pLevel1, pPos, pState1);
//                });
//    }
}
