package net.boat.industrialhellscape.block.modded_block_classes.ContainerBlocks;

import net.boat.industrialhellscape.block.modded_block_entity_registrations.GenericContainerBE;
import net.boat.industrialhellscape.block.modded_interfaces.ContainerBlockCapability;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.DirectionProperty;
import net.minecraft.world.phys.BlockHitResult;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

//INFO:
//-----
//This block supports cardinal directional placement, and an inventory with GUI. The inventory size is determined upon block registration.
//It extends the vanilla block class, Horizontal DirectionalBlock, and implements the vanilla interface, EntityBlock
//
//-----

public class FacingContainerBlock extends HorizontalDirectionalBlock implements EntityBlock {
    public final int SLOTS; //Amount of inventory slots. Should be a multiple of 9.
    public final SoundEvent OPEN_SOUND;
    public final SoundEvent CLOSE_SOUND;

    private static final DirectionProperty FACING = BlockStateProperties.HORIZONTAL_FACING;

    public FacingContainerBlock(Properties properties, int SlotAmount, SoundEvent openSound, SoundEvent closeSound) {
        super(properties);
        this.SLOTS = SlotAmount; //The inventory capacity of the block is determined during registration
        this.OPEN_SOUND = openSound;
        this.CLOSE_SOUND = closeSound;

        this.registerDefaultState(this.stateDefinition.any()
                .setValue(FACING, Direction.NORTH)
        );
    }

    @Override
    public @Nullable BlockState getStateForPlacement(BlockPlaceContext pContext) {
        BlockState state = defaultBlockState();
        Direction directionClicked = pContext.getHorizontalDirection().getOpposite(); //Gets the cardinal direction when player places new block
        //The autogenerated block item models show the "front" of the block as the right side.
        //In-world, this side faces away from the player when placed, which is not intuitive.
        //getOpposite() is used to rectify in-world placement while keeping any auto-generated asymmetric textured full-block models consistent.
        state = state.setValue(FACING, directionClicked); //Defines facing direction of the block
        return state;
    }

    @Override
    protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
        builder.add(FACING);
    }

    //---------- Block Entity Handling Methods below ----------

    @Nullable
    @Override
    public BlockEntity newBlockEntity(@NotNull BlockPos pos, @NotNull BlockState state) {
        return new GenericContainerBE(pos, state);
    }

    @NotNull
    @Override
    public InteractionResult use(@NotNull BlockState state, @NotNull Level level, @NotNull BlockPos pos, @NotNull Player player, @NotNull InteractionHand hand, @NotNull BlockHitResult hit) {
        return ContainerBlockCapability.OpenContainerInventory(level,pos,player);
    }

    @Override
    public void onRemove(@NotNull BlockState state, @NotNull Level level, @NotNull BlockPos pos, @NotNull BlockState newState, boolean isMoving) {
        //General method for safe removal of current (Container) and deprecated block entities.
        //Handles both the new container entities and previous non-container block entities
        ContainerBlockCapability.dropSavedContainerInventory(this, state, level, pos, newState);
        super.onRemove(state, level, pos, newState, isMoving);
    }

    //---------- End of Block Entity Handling Methods ----------
}