package net.boat.industrialhellscape.block.modded_block_classes.StorageBlocks;

import net.minecraft.core.Direction;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.EntityBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.BooleanProperty;
import net.minecraft.world.level.block.state.properties.DirectionProperty;
import org.jetbrains.annotations.Nullable;

import java.util.function.Supplier;

//INFO:
//-----
//This block supports cardinal directional placement, and an inventory with GUI. The inventory size is determined upon block registration.
//Block has a block entity within.

//getSlotCount() used by StorageBlockInterface to detect desired Block Entity item slot amount to create.
//getOpenSound() and getClosedSound() used by StorageBlockInterface to detect desired sounds for opening and closing Block Entity menu.
//If I define these block states in the interfaces, it may crash in 1.21. This is why these methods are in place.

public class FacingStorageBlock extends BaseStorageBlock implements EntityBlock {
    public static final BooleanProperty OPEN = BlockStateProperties.OPEN;
    public final int SLOTS;
    public final Supplier<SoundEvent> OPEN_SOUND;
    public final Supplier<SoundEvent> CLOSE_SOUND;

    private static final DirectionProperty FACING = BlockStateProperties.HORIZONTAL_FACING;

    public FacingStorageBlock(Properties properties, int slotsAmount, Supplier<SoundEvent> openSound, Supplier<SoundEvent> closeSound) {
        // When registering this block, pass in
        // Properties
        // Integer amount of slots the block entity inventory will have (multiple of 9)
        // Sound to play when player opens block
        // Sound to play when player closes block

        super(properties, slotsAmount, openSound, closeSound);
        this.SLOTS = slotsAmount;
        this.OPEN_SOUND = openSound;
        this.CLOSE_SOUND = closeSound;
        this.registerDefaultState(this.stateDefinition.any().setValue(OPEN, false));

        this.registerDefaultState(this.stateDefinition.any()
                .setValue(FACING, Direction.NORTH)
                .setValue(OPEN, false)
        );
    }

    @Override
    public int getSlotCount() {
        return SLOTS;
    }

    @Override
    public Supplier<SoundEvent> getOpenSound() {
        return OPEN_SOUND;
    }

    @Override
    public Supplier<SoundEvent> getCloseSound() {
        return CLOSE_SOUND;
    }

    @Override
    public @Nullable BlockState getStateForPlacement(BlockPlaceContext pContext) {
        BlockState state = defaultBlockState();
        Direction directionClicked = pContext.getHorizontalDirection().getOpposite(); //Gets the cardinal direction when player places new block
        //The autogenerated block item models show the "front" of the block as the right side.
        //In-world, this side faces away from the player when placed, which is not intuitive.
        //getOpposite() is used to rectify in-world placement while keeping any auto-generated asymmetric textured full-block models consistent.
        state = state.setValue(FACING, directionClicked); //Defines facing direction of the block
        return state;
    }

    @Override
    protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
        builder.add(FACING, OPEN);
    }

    //---------- Block Entity Handling Methods below ----------
    //---------- End of Block Entity Handling Methods ----------
}